config/routes.rb
Rails.application.routes.draw do
	devise_for :accounts
	resources :properties

	#admin routes
	get "/accounts" => 'admin#accounts', as: :accounts
	
	get "/dashboard" => 'dashboard#index', as: :dashboard
	get "/profile/:id" => 'dashboard#profile', as: :profile
	post "/agent/message" => "properties#email_agent", as: :email_agent
	
	root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  mount_uploader :image, ProfilePictureUploader

  has_many :properties

  def full_name
  	"#{first_name} #{last_name}"
  end

  def company
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
	mount_uploader :photo, PhotoUploader
	belongs_to :account

	scope :latest, -> { order created_at: :desc }

	scope :sold, -> { where(for_sale: true, status: "sold") }
	scope :for_sale, -> { where(for_sale: true, status: "available") }
	scope :leased, -> { where(for_sale: false, status: "leased") }
	scope :for_rent, -> { where(for_sale: false, status: "available") }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :can_access?

	def accounts
		@accounts = Account.where(admin: false)
	end

	def can_access?
		@show_sidebar = true

		unless current_account.admin?
			redirect_to root_url, flash: { danger: "You do not have access to view this page" }
		end
	end
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :telephone, :url, :image, :image_cache, :company])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :set_sidebar

	def index
	end

	def profile
		@account = Account.find(params[:id])
		@properties = Property.where(account_id: @account.id)

		@properties_sold = Property.where(account_id: @account.id).sold.count
		@properties_for_sale = Property.where(account_id: @account.id).for_sale.count
		@properties_leased = Property.where(account_id: @account.id).leased.count
		@properties_for_rent = Property.where(account_id: @account.id).for_rent.count
	end

	private
	def set_sidebar
		@show_sidebar = true if account_signed_in?
	end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new, :create, :destroy]
  before_action :set_sidebar, except: [:show]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @agent = @property.account
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id)
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def email_agent
    # trigger email send
    agent_id = params[:agent_id]
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    message = params[:message]

    ContactMailer.email_agent( agent_id, first_name, last_name, email, message ).deliver_now

    # response to script
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    def set_sidebar
        @show_sidebar = true
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :parking_spaces, :for_sale, :available_date, :details, :photo, :photo_cache)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
	def main
		if account_signed_in?
			path = current_account.admin? ? accounts_path : dashboard_path
			redirect_to path, flash: { success: "Successfully singed in. Welcome to Property Finder!" } and return
		end

		@properties = Property.latest
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def profile_picture account, width = 100
		thumb = account.image.present? ? account.image.thumb.url : "https://via.placeholder.com/100C/O https://placeholder.com/"
		image_tag thumb, width: width, class: "profile-pic img-circle"
	end

	def flash_notifications
		flash_messages = []
		flash.each do |type, message|
			type = 'success' if type == 'notice'
			type = 'error' 	 if type == 'alert' || type == 'danger'
			text = "toastr['#{type}']('#{message}');"
			flash_messages << text.html_safe unless message.blank?
		end

		"<script>$(function(){ #{ flash_messages.join("\n") } });</script>".html_safe if flash_messages.any?
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
	def property_thumbnail property
		img = property.photo.present? ? property.photo.thumb.url : "https://source.unsplash.com/sqc9yv6iueE/350x200"
		image_tag img, class: "property_thumb"
	end

	def property_photo_url property
		property.photo.present? ? property.photo.url : "https://source.unsplash.com/561igiTyvSk/"
	end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/accounts.html.erb
<div class="container p-5 mt-5">
	<h2>Accounts</h2>

	<% @accounts.each do |account| %>
	<div class="row">
		<div class="col-sm-3">
			<%= account.full_name %>
		</div>
		<div class="col-sm-3">
			<%= account.email %>
		</div>
		<div class="col-sm-3">
			<%= account.created_at.strftime("%d, %m, %Y") %>
		</div>
		<div class="col-sm-3">
			<%= link_to "View profile", profile_path(account.id) %>
		</div>
	</div>
	<% end %>
</div>

app/views/dashboard/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h3">Dashboard</h1>
	<div class="btn-toolbar mb-2 mb-md-0">
		<div class="btn-group mr-2">
			<button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
			<button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
		</div>
		<button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar">
				<rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
				<line x1="16" y1="2" x2="16" y2="6"></line>
				<line x1="8" y1="2" x2="8" y2="6"></line>
				<line x1="3" y1="10" x2="21" y2="10"></line>
			</svg>
			This week
		</button>
	</div>
</div>
<div class="table-responsive">
	<table class="table table-striped table-sm">
		<thead>
			<tr>
				<th>#</th>
				<th>Header</th>
				<th>Header</th>
				<th>Header</th>
				<th>Header</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1,001</td>
				<td>Lorem</td>
				<td>ipsum</td>
				<td>dolor</td>
				<td>sit</td>
			</tr>
			<tr>
				<td>1,002</td>
				<td>amet</td>
				<td>consectetur</td>
				<td>adipiscing</td>
				<td>elit</td>
			</tr>
			<tr>
				<td>1,003</td>
				<td>Integer</td>
				<td>nec</td>
				<td>odio</td>
				<td>Praesent</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="container">
	<p>&copy; Property-Finder 2020</p>
</footer>

app/views/layouts/_validation.html.erb
<% if item.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(item.errors.count, "error") %> prohibited this property from being saved:</h2>

		<ul>
			<% item.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>PropertyFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"> -->
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_url "favicon_io/apple-touch-icon.png" %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_url "favicon_io/favicon-32x32.png" %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_url "favicon_io/favicon-16x16.png" %>">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= flash_notifications %>

</head>

<body id="<%= controller.controller_name %>" class="<%= controller.action_name %> <%= "show-sidebar" if @show_sidebar.present? %>">
    <% if @show_sidebar.nil? %>
    <header>
        <%= render "layouts/nav/public" %>
        <%= yield %>
    </header>
    <% else %>
    <%= render "layouts/nav/dashboard" %>

    <div class="container-fluid">
        <div class="row">
            <%= render "layouts/nav/sidebar" %>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-4">
                <%= yield %>
            </main>
        </div>
    </div>
    <% end %>



    <%#= render "layouts/footer" %>

    <div id="notifications">
        <%= flash_notifications %>
    </div>

</body>
</html>

app/views/layouts/nav/_admin.html.erb
<li class="nav-item">
	<%= link_to accounts_path, class: "nav-link" do %>
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
		Accounts <span class="sr-only">(current)</span>
	<% end %>
</li>
<li class="nav-item">
	<%= link_to properties_path, class: "nav-link" do %>
	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
	Properties
	<% end %>
</li>
<li class="nav-item">
	<a class="nav-link" href="#">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
		Blog Posts
	</a>
</li>
<li class="nav-item">
	<a class="nav-link" href="#">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
		Adverts
	</a>
</li>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
	<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Property Finder</a>
	<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
	<ul class="navbar-nav px-3">
		<li class="nav-item text-nowrap">
			<%= link_to "Log Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">Property Finder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <% if account_signed_in? %>
                <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
                <% else %>
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                <% end %>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Latest</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">News</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Advertising</a>
            </li>
            <% if account_signed_in? %>
            <li class="nav-item">
                <%= link_to "Log Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Log In", new_account_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
            </li>
            <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
	<div class="sidebar-sticky">
		<ul class="nav flex-column">
			<%= render "layouts/nav/#{ current_account.admin? ? 'admin' : 'user' }" %>
		</ul>
		<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
			<span>Settings</span>
		</h6>
		<ul class="nav flex-column mb-2">
			<li class="nav-item">
				<%= link_to profile_path(current_account), class: "nav-link" do %>
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-activity"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
				My Profile
				<% end %>
			</li>
			<li class="nav-item">
				<%= link_to edit_account_registration_path, class: "nav-link" do %>
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-activity"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
				Account Settings
				<% end %>
			</li>
		</ul>
	</div>
</nav>

app/views/layouts/nav/_user.html.erb
<li class="nav-item">
	<%= link_to dashboard_path, class: "nav-link" do %>
	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
	Dashboard <span class="sr-only">(current)</span>
	<% end %>
</li>
<li class="nav-item">
	<%= link_to properties_path, class: "nav-link" do %>
	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
	Properties
	<% end %>
</li>
<li class="nav-item">
	<a class="nav-link" href="#">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
		Products
	</a>
</li>
<li class="nav-item">
	<a class="nav-link" href="#">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
		Contacts
	</a>
</li>

app/views/properties/_agent_details.html.erb
<div class="">
	<div class="text-center border pt-4 pb-4 ml-lg-4 p-3">
		<div class="mb-2">
			<%= profile_picture agent %>
		</div>
		<h3 class="h4 m-0"><%= agent.full_name %></h3>
		<p><%= @agent.company %></p>

		<div class="row">
			<div class="col-12">
				<button class="btn btn-block btn-info text-uppercase mb-3" id="show-tel" data-telephone="<%= agent.telephone %>"><i class="fa fa-phone mr-2"></i><span>Call</span></button>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 pr-1">
				<%= link_to "Profile", profile_path(agent.id), class: "btn btn-block btn-secondary text-uppercase" %>
			</div>

			<div class="col-md-6 pl-1">
				<button class="btn btn-block btn-success text-uppercase" data-toggle="modal" data-target="#contact-modal">Email</button>
			</div>
		</div>
	</div>
</div>

app/views/properties/_list.html.erb
<% properties.each do |property| %>
<div class="col-4 py-3">
	<div class="property border">
		<%= link_to(property_thumbnail(property), property_path(property)) %>
		<div class="property-summary p-3">
			<h3 class="h5 mt-3 text-dark"><%= link_to property.name, property_path(property) %></h3>
			<span class="mr-2">
				<%= property.rooms %>
				<i class="fa fa-bed ml-1" aria-hidden="true"></i> 
			</span>
			<span class="mr-2">
				<%= property.bathrooms %>
				<i class="fa fa-bath ml-1" aria-hidden="true"></i> 
			</span>	
			<span class="mr-2">
				<%= property.parking_spaces %>
				<i class="fa fa-car ml-1" aria-hidden="true"></i> 
			</span>
			<p class="mt-2"><%= property.address %></p>
		</div>
	</div>
</div>
<% end %>

app/views/properties/_send_email_modal.html.erb
<div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Message for <%= @agent.first_name %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <%= form_tag email_agent_path, id: "email-agent" do %>
                    <%= hidden_field_tag :agent_id, @agent.id %>

                    <div class="form-group">
                        <label for="message-first-name" class="col-form-label">First Name:</label>
                        <%= text_field_tag :first_name, nil, class: "form-control", id: "message-first-name" %>
                    </div>

                    <div class="form-group">
                        <label for="message-last-name" class="col-form-label">Last Name:</label>
                        <%= text_field_tag :last_name, nil, class: "form-control", id: "message-last-name" %>
                    </div>

                    <div class="form-group">
                        <label for="message-email" class="col-form-label">Email:</label>
                        <%= text_field_tag :email, nil, class: "form-control", id: "message-email" %>
                    </div>

                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Message:</label>
                        <textarea class="form-control" id="message-text"></textarea>
                    </div>
                <% end %>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    Close
                </button>
                <button type="button" class="btn btn-success" id="send-message-to-agent">
                    Send message
                </button>
            </div>
        </div>
    </div>
</div>

app/views/properties/edit.html.erb
<h1 class="h3">Editing Property</h1>

<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<h1 class="h3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
  </tr>
</thead>

<tbody>
    <% @properties.each do |property| %>
    <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: "btn btn-success btn-sm" %>

app/views/properties/new.html.erb
<h1 class="h3">New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>